import { createContext, useContext, useState, useEffect, useMemo } from 'react';

const translations = {
  en: {
    nav: {
      status: 'Open to Roles',
      statusSub: 'Senior · Lead · Remote · International',
      menu: 'MENU +',
      logoLabel: 'ByAndresFe — back to home',
      logoSub: 'ByAndresFe',
      work: 'Work',
      about: 'About',
      resume: 'Resume',
      notes: 'Notes',
      contact: 'Contact',
      lang: 'ES',
    },
    hero: {
      label: 'UX Lead / Game UX/UI Designer',
      signalActive: 'SIGNAL ACTIVE',
      focusAreasLabel: 'Current focus areas',
      subtitle: 'Designing experiences\nthat leave\na mark.',
      body: 'I design interfaces, flows, and UX systems for games, digital products, and interactive experiences. My work connects clarity, feedback, production constraints, and player decision-making.',
      cta1: 'View selected work',
      cta2: 'About Me',
      proof: 'Senior Game UX/UI Designer & UX Lead · 11+ years · Shipped VR on Meta Quest and licensed-IP experiences in Fortnite / UEFN — Dungeons & Dragons, Star Wars, The Walking Dead.',
      tags: ['VR UX', 'UEFN', 'Unreal', 'Roblox', 'HUD Systems', 'UI Systems', 'Player Clarity', 'Accessibility', 'Production Handoff'],
    },
    labHero: {
      navLinks: ['Work', 'About', 'Approach', 'Experience', 'Contact'],
      availability: 'Open to senior roles',
      nameplate: "I'm Andrés Felipe Pisso",
      titleLines: ['Designing', 'Experiences', 'That Leave A Mark'],
      roles: ['UX/UI Designer', 'Game Designer', 'Product Designer'],
      cta: 'Explore My Work',
      scroll: 'Scroll',
      revealHint: 'move cursor to reveal',
      skills: ['UX / UI Design', 'Game Design', 'Product Design'],
      rightCopy: ['I design game UX', 'for shipped VR and', 'Fortnite titles —', 'D&D, Star Wars, TWD.'],
      basedInLabel: 'Based in Earth',
      coordinates: '4.7110° N, 74.0721° W',
      systemsLabel: 'Systems',
      systemsStatus: 'All green',
      responseLabel: 'Response',
      interfaceMode: '// Interface_mode',
      phaseActive: 'Active',
      phaseScanning: 'Scanning',
      phaseBoot: 'Boot',
      statusLabel: 'Status',
      online: 'Online',
      locationLabel: 'Location',
      locationValue: 'Bogotá, Colombia',
      availableForWork: 'Available for work',
    },
    trust: {
      label: 'Track record',
      stats: [
        { value: '11+', label: 'Years of experience' },
        { value: '70+', label: 'Interactive projects' },
        { value: '8+', label: 'Game UX/UI case studies' },
        { value: '3+', label: 'Shipped game experiences' },
      ],
    },
    whatIDo: {
      label: 'What I do',
      sectionTitle: 'Three domains.\nOne constraint.',
      headline: 'Design across three domains.',
      items: [
        {
          title: 'Game UX/UI',
          body: 'HUDs, menus, onboarding, feedback systems, player flows, readability, and progression clarity.',
          tags: ['VR', 'UEFN', 'Unreal', 'Roblox', 'HUD', 'Onboarding', 'Fortnite'],
        },
        {
          title: 'UX Systems',
          body: 'Reusable UI patterns, states, components, interaction rules, documentation, and handoff.',
          tags: ['Components', 'Design Systems', 'Handoff', 'Documentation'],
        },
        {
          title: 'Digital Product',
          body: 'Information architecture, flows, prototypes, interface design, usability, and product clarity.',
          tags: ['IA', 'Wireframes', 'Prototyping', 'Usability'],
        },
      ],
    },
    howIWork: {
      label: 'How I work',
      sectionTitle: 'From hesitation\nto signal.',
      headline: 'From hesitation to signal.',
      body: 'Every project starts with a loop, a gap, and a signal. Systematic, not decorative.',
      steps: [
        { num: '01', title: 'Understand the loop', body: 'Map the player or user journey. Identify where actions, consequences, and feedback happen.' },
        { num: '02', title: 'Find where hesitation starts', body: 'Locate the friction points. What forces a guess? What creates doubt or confusion?' },
        { num: '03', title: 'Design the signal', body: 'Build the interface response that removes the guesswork. Clear feedback, better hierarchy, faster decisions.' },
        { num: '04', title: 'Test the decision', body: 'Validate the design against the problem. Does it reduce hesitation? Does the player or user move forward with confidence?' },
        { num: '05', title: 'Document the system', body: 'Turn decisions into reusable rules. Components, states, handoff specs, and edge case notes the team can act on.' },
      ],
    },
    caseFiles: {
      label: 'Selected Work',
      sectionTitle: 'DESIGN WITH REAL CONTEXT.\nSYSTEMS, INTERFACES AND DECISIONS.',
      headline: 'Case files.',
      descriptionShort: 'A selection of projects where design didn\'t happen under ideal conditions, but within real product objectives, constraints and needs. Some cases are public; others are presented in NDA-safe format to show the thinking behind the work without compromising sensitive information.',
      description: 'A selection of projects where design didn\'t happen under ideal conditions, but within real product objectives, constraints and needs. Some cases are public; others are presented in NDA-safe format to show the thinking behind the work without compromising sensitive information.',
      viewAll: 'View all work',
      openCase: 'Open case',
      metaRole: 'Role',
      metaYear: 'Year',
      metaFocus: 'Focus',
      project: 'project',
      projects: 'projects',
      noProjects: 'No projects match this filter.',
      filterLabels: { All: 'All', Games: 'Games', UEFN: 'UEFN', VR: 'VR', 'NDA-Safe': 'NDA-Safe', Legacy: 'Archive' },
      filterNav: 'Filter projects',
      casesRegionLabel: 'Case studies',
    },
    systemsLab: {
      label: 'Systems Lab',
      sectionTitle: 'Constraints,\nnot values.',
      principlesLabel: 'Design principles',
      modulesLabel: 'Active work modules',
      description: 'These are not aspirational values. They are practical constraints applied to every design decision. They exist because game UX fails in predictable ways, and these principles address the most common failure modes.',
      principles: [
        { id: '01', title: 'Clarity before polish', body: 'If a player has to read something twice to understand it, the visual finish does not matter. Clarity ships first.' },
        { id: '02', title: 'Feedback before guesswork', body: 'The player should always know what happened, what is happening and what will happen next. If they are guessing, the interface has failed.' },
        { id: '03', title: 'Systems before isolated screens', body: 'Designing a single screen without understanding its connected states produces interfaces that work in demos and break in production.' },
        { id: '04', title: 'Useful before decorative', body: 'Motion, color and visual detail earn their place by communicating something. Decoration that carries no signal is noise.' },
        { id: '05', title: 'Better signals, better decisions', body: 'The output of good UX is not a beautiful screen. It is a player who made the right decision with less friction than before.' },
      ],
      modules: [
        { label: 'HUD Reviews', tag: 'Analysis' },
        { label: 'UX Systems', tag: 'Architecture' },
        { label: 'UI Components & States', tag: 'Systems' },
        { label: 'Accessibility Reviews', tag: 'Compliance' },
        { label: 'Player Onboarding', tag: 'Flows' },
        { label: 'LiveOps UX', tag: 'Product' },
        { label: 'Figma Workflows', tag: 'Tools' },
        { label: 'UEFN Workflows', tag: 'Platform' },
        { label: 'Documentation', tag: 'Handoff' },
      ],
    },
    igStrip: {
      label: 'In the field',
      viewProfile: 'View profile',
      viewPost: 'View on Instagram',
    },
    fieldNotes: {
      label: 'Field Notes',
      sectionTitle: 'Applied.\nNot theoretical.',
      headline: 'Notes and frameworks.',
      description: 'Breakdowns, frameworks, and reference material built from working on real game UX problems. Not theory. Tested in production.',
      readNote: 'Read note',
      viewAll: 'View all notes',
    },
    about: {
      label: 'About',
      sectionTitle: 'Where clarity\nbreaks.',
      fullProfile: 'Full profile',
      headline: 'Where does clarity break?',
      bio1: 'I started in systems engineering and ended up building the feedback loops players never notice when they work. Eleven years across shipped games, UEFN live experiences, VR, and digital product.',
      bio2: 'My work starts with one question: where does clarity break? In games, it shows up as a HUD pulling attention from the action, a reward flow that creates hesitation, a progression system that makes players guess what changed. In product it is unclear navigation, weak feedback, screens that look clean but do not help anyone decide.',
      bio3: 'I care about interfaces that reduce doubt. Clear signals. Useful feedback. Systems that help teams move faster without losing consistency.',
      coreQuestion: '"Where is the player guessing?"',
      coreQuestionLabel: 'Core question',
      philosophy: 'Good game UX is not invisible. It is present and clear enough that the player never has to think about the interface.',
      philosophyLabel: 'Design philosophy',
      availabilityLabel: 'Availability',
      availabilityStatus: 'Open to Senior Game UX/UI, UX/UI Lead, and Game UI Systems roles',
      availabilityContext: 'Remote · Hybrid · International studios — Senior & Lead positions',
      availabilityCta: 'Get in touch',
      expertiseLabel: 'Expertise areas',
      timelineLabel: 'Career path',
      languagesLabel: 'Languages',
      languages: ['Spanish — Native', 'English — Advanced professional working proficiency'],
      educationLabel: 'Education',
      education: [
        { year: '2023', degree: "Master's in Digital Graphic Design", institution: 'UNIR — Universidad Internacional de La Rioja' },
        { year: '2019', degree: 'Specialist in Information Systems Audit', institution: 'Universidad Católica de Colombia' },
        { year: '2016', degree: 'Specialist in Game Design and Development', institution: 'Michigan State University' },
        { year: '2015', degree: 'Systems Engineer', institution: 'Universidad Cooperativa de Colombia' },
      ],
      certificationsLabel: 'Certifications',
      certifications: [
        { year: '2024', label: 'Epic Games Game Design Professional Certificate', note: 'In progress' },
        { year: '2015', label: 'Gamification', note: 'University of Pennsylvania' },
      ],
      timeline: [
        { period: '2025 – Now', role: 'Lead UX/UI Designer', context: 'Teravision Games · Orcs Must Die, UEFN, VR, D&D' },
        { period: '2023 – 2025', role: 'Lead Game Designer', context: 'PixieMeta · Mobile games, UX systems' },
        { period: '2022 – 2023', role: 'Technology & Adoption Lead', context: 'Ministry of ICT Colombia · Digital transformation, GAMETIC' },
        { period: '2016 – 2022', role: 'Game Designer / Systems Engineer', context: 'Ministry of ICT Colombia · 70+ apps, 20 games, GAMETIC' },
        { period: '2015 – 2016', role: 'Game Designer / Project Director', context: 'Universidad Cooperativa · Kodety — Colombia Crea Digital winner' },
      ],
      hiringSnapshot: 'Senior Game UX/UI Designer and UX Lead with 11+ years across games, digital products, and interactive experiences. I specialize in UI systems, HUD clarity, VR UX, UEFN experiences, onboarding, progression flows, player feedback, accessibility, and production-ready documentation. My work connects player understanding with team execution through clear flows, reusable components, readable interfaces, and implementation-ready handoff.',
      hiringSnapshotLabel: 'Hiring Snapshot',
      hiringSnapshotRoles: 'Open to Senior Game UX/UI Designer, UX/UI Lead, Game UI Systems Designer, and UX Lead roles across remote, hybrid, and international teams.',
      recruiterSummaryLabel: 'Recruiter Summary',
      recruiterSummaryTargetLabel: 'Target roles',
      recruiterSummaryTarget: 'Senior Game UX/UI Designer · UX/UI Lead · Game UI Systems Designer · UX Lead',
      recruiterSummaryStrengthsLabel: 'Core strengths',
      recruiterSummaryStrengths: [
        'Game UX/UI strategy and systems design',
        'UI systems, component logic and reusable pattern libraries',
        'HUD clarity, player feedback and readability',
        'VR UX and spatial interface considerations',
        'UEFN and Unreal-aware design and handoff',
        'Onboarding, FTUX and progression flows',
        'Accessibility and interface readability',
        'Production-ready documentation for design, art, engineering, QA and production',
        'Cross-functional collaboration across disciplines',
      ],
      recruiterSummaryToolsLabel: 'Tools',
      recruiterSummaryTools: 'Figma · Unreal Engine · UEFN context · Roblox · Jira · Confluence · Adobe Creative Suite · prototyping tools · documentation systems',
      recruiterSummaryTeamsLabel: 'Best-fit teams',
      recruiterSummaryTeams: 'Game studios · UEFN teams · VR projects · live games · licensed IP experiences · UI systems teams · UX teams working closely with implementation',
      seniorValueLabel: 'Why this matters for senior roles',
      seniorValue: 'Senior Game UX/UI work is not only about making interfaces look polished. It is about helping players understand what matters, helping teams reuse decisions, reducing production ambiguity, and designing systems that survive iteration. My strongest work sits at that intersection: player clarity, UI systems, documentation, implementation handoff, and cross-functional collaboration.',
      aboutCtaHeadline: 'If your team is building something players need to understand,',
      aboutCtaAccent: 'I can help.',
      aboutCtaEmail: 'Send a signal',
      aboutCtaLinkedIn: 'LinkedIn',
      resumeBtn: 'Download Resume — Senior Game UX/UI / UX Lead',
      expertise: [
        'Game UX/UI', 'UX Leadership', 'UI Systems', 'Product Thinking',
        'Game Design', 'Documentation', 'Accessibility', 'UEFN / Unreal',
        'Cross-functional collaboration', 'Player Onboarding', 'HUD Design', 'LiveOps UX', 'VR UX',
      ],
      skillGroups: [
        { title: 'Game UX/UI', items: ['HUD', 'Menus', 'Onboarding', 'Progression', 'Reward flows', 'Feedback', 'Readability', 'Player loops', 'VR UX', 'UEFN UX'] },
        { title: 'UX Systems', items: ['Design systems', 'Components', 'States', 'Patterns', 'Documentation', 'Handoff', 'QA support', 'Accessibility checks'] },
        { title: 'Product UX/UI', items: ['Information architecture', 'Flows', 'Wireframes', 'Prototypes', 'Usability', 'Interface design', 'Stakeholder alignment'] },
        { title: 'Tools', items: ['Figma', 'FigJam', 'UEFN', 'Unreal', 'Roblox', 'Claude', 'Jira', 'Confluence', 'Adobe tools', 'Prototyping tools'] },
      ],
    },
    contact: {
      label: 'Signal Contact',
      channelsLabel: 'Contact channels',
      linkedinCta: 'Schedule a call on LinkedIn',
      contactMe: 'Contact me →',
      headline: "I’m open to Senior Game UX/UI, UX Lead, UX/UI Lead, and Game UI Systems roles across remote, hybrid, and international teams.",
      ctaLine1: "Let’s build",
      ctaStroke: "clearer game",
      ctaLine3: "experiences.",
      cta: 'Send a signal',
      email: 'hi@byandresfe.com',
      linkedin: 'linkedin.com/in/byandresfe',
      instagram: '@byandresfe',
      x: '@byandresfe',
      location: 'Colombia — remote & international',
      formLabels: {
        name: 'Name',
        email: 'Email',
        company: 'Company or studio',
        type: 'Type of opportunity',
        message: 'Message',
        send: 'Send message',
        sending: 'Sending...',
        success: 'Message received. I will reply within a few days.',
      },
      opportunityTypes: ['Studio role', 'Product role', 'Freelance project', 'Consulting', 'Speaking or workshop', 'Other'],
    },
    footer: {
      tagline: 'Game UX/UI and product design focused on clarity, feedback, and better decisions.',
      links: ['Work', 'About', 'Resume', 'Notes', 'Contact'],
      copy: '© 2026 Andrés Felipe Pisso',
      handle: '@byandresfe',
      navWork: 'Work',
      navConnect: 'Connect',
      resume: 'Resume',
    },
    resume: {
      label: 'Resume',
      headline: 'Andrés Felipe Pisso',
      subheadline: 'UX Lead · Game UX/UI Designer',
      download: 'Download PDF',
      sections: {
        summary: 'Summary',
        experience: 'Selected experience',
        projects: 'Selected projects',
        skills: 'Skills',
        tools: 'Tools',
        education: 'Education',
        languages: 'Languages',
        contact: 'Contact',
      },
      summary: '11+ years designing UX/UI systems for games, digital products, and interactive experiences. Focused on clarity, feedback, player decision-making, and production-ready interfaces. Experience across VR, UEFN, mobile, and digital product.',
      experience: [
        {
          period: '2025 – Present',
          role: 'Lead UX/UI Designer',
          company: 'Teravision Games',
          description: 'UX Lead across shipped game projects, Fortnite / UEFN live experiences, and VR productions. Responsible for UX strategy, UI system design, design documentation, and cross-discipline collaboration.',
        },
        {
          period: '2023 – 2025',
          role: 'Lead Game Designer',
          company: 'PixieMeta',
          description: 'Defined and maintained creative vision for mobile games, aligning gameplay systems, user flows and UI/UX decisions with audience needs and business goals.',
        },
        {
          period: '2016 – 2023',
          role: 'Systems Engineer / Game Designer / UX Designer',
          company: 'Various organizations',
          description: 'Game design, interaction design, UI/UX, and digital product work across government technology initiatives, educational platforms, and interactive web experiences.',
        },
      ],
      projects: [
        { title: 'Star Wars: Roguelike One', type: 'UEFN / Game UX/UI', year: '2026' },
        { title: 'Orcs Must Die: By the Blade', type: 'VR Game UX/UI', year: '2025–2026' },
        { title: 'D&D: Zombie Dragon Adventure', type: 'UEFN / Game UX/UI', year: '2025' },
        { title: 'The Walking Dead: Courtyard King', type: 'UEFN / Game UX/UI', year: '2025' },
        { title: 'Raptor Heist', type: 'UEFN / Game UX/UI', year: '2025' },
        { title: 'Havoc Hotel 3', type: 'UEFN / UX Systems', year: '2025' },
      ],
      languageList: ['Spanish — Native', 'English — Professional'],
      locationRemote: 'Colombia — Remote',
    },
    casePage: {
      notFound: 'Case not found.',
      backToWork: '← Back to work',
      metaRole: 'Role',
      metaPlatform: 'Platform',
      metaYear: 'Year',
      quickFacts: 'Quick facts',
      prev: '← Prev',
      next: 'Next →',
      sections: {
        executiveSummary: 'Executive summary',
        context: 'Context',
        challenge: 'The challenge',
        myRole: 'My role',
        constraints: 'Constraints',
        uxApproach: 'UX approach',
        keyDecisions: 'Key decisions',
        keyDecisionsIntro: 'These are the design choices that shaped the most important UX outcomes of the project.',
        problem: 'Problem',
        decision: 'Decision',
        whyItMattered: 'Why it mattered',
        deliverables: 'Deliverables',
        outcome: 'Outcome',
        projectSnapshot: 'Project Snapshot',
        myOwnership: 'My Ownership',
        impact: 'Impact / Evidence',
        implementationHandoff: 'Implementation & Handoff',
        researchValidation: 'Research & Validation',
        nextSteps: 'What I would check next',
        whatThisShows: 'What this project shows',
        featuredSystems: 'Featured systems',
        beforeAfter: 'Before and after',
        whatILearned: 'What I learned',
        playerExperienceLoop: 'Player experience loop',
      },
      fieldLabels: {
        role: 'Role',
        studio: 'Studio',
        client: 'Client',
        IP: 'IP',
        platform: 'Platform',
        type: 'Type',
        duration: 'Duration',
        team: 'Team',
        tools: 'Tools',
        status: 'Status',
        engine: 'Engine',
        context: 'Context',
        mainChallenge: 'Main Challenge',
        keyDeliverables: 'Key Deliverables',
        constraints: 'Constraints',
      },
    },
    notFound: {
      tag: 'Error 404',
      subtitle: 'Page disconnected.',
      bodyPrefix: 'The page at',
      bodySuffix: 'is offline. We found the problem — a tiny brown suspect escaped with the power cable before this page could load.',
      logs: [
        'PAGE_STATUS: OFFLINE',
        "CABLE_STATUS: IN DOG'S MOUTH",
        'OPERATOR_STATUS: PANICKING',
        'SUSPECT_DESCRIPTION: BROWN, FAST, WEARING HOODIE',
        'RECOVERY_PLAN: RUN FASTER',
      ],
      cta: 'Restore Connection',
      pageTitle: 'Page Not Found — AFPISSO',
      pageDesc: 'The page you were looking for has gone missing. A dog may be involved.',
    },
    aboutPage: {
      subheadline: 'UX Lead · Game UX/UI Designer',
    },
    contactOverlay: {
      signalContact: 'Signal Contact',
      directChannel: 'DIRECT CHANNEL',
      primaryChannel: 'Primary channel',
      writeCta: 'WRITE →',
      tagProfessional: 'Professional',
      tagCreative: 'Creative',
      tagSignal: 'Signal',
    },
    notePage: {
      comingSoon: 'This note will be available soon.',
      notFound: 'Note not found.',
      backToNotes: 'Back to Field Notes',
      aboutNote: 'About this note',
      metaId: 'ID',
      metaType: 'Type',
      metaReadTime: 'Read time',
      metaCategory: 'Category',
      metaPublished: 'Published',
      nextNote: 'Next note',
      fieldNotesLabel: 'Field Notes',
      subscribeHeadline: 'Get new field notes',
      subscribeBody: 'Game UX, UI systems, accessibility and design decisions. No spam.',
      subscribePlaceholder: 'your@email.com',
      subscribeCta: 'Subscribe',
      subscribeSuccess: 'I will reply soon.',
      relatedCaseStudies: 'Related Case Studies',
      openCase: 'Open case',
      allNotes: 'All field notes',
      nextNoteCta: 'Next note',
    },
    casePage_cta: {
      body: 'If my work fits your team or project, reaching out should take less than a minute.',
    },
    speaking: {
      sectionLabel: 'Speaking & Workshops',
      heroSubtitle: 'Game UI Systems: from pretty screens to interfaces that work.',
      contextLabel: 'The workshop',
      bodyP1: 'At Colombia 5.0, I ran a workshop on Game UI Systems: specifically on how to build a reusable, functional UI system for video games using Figma. The premise: most game interfaces look polished but break under real production conditions because they were designed as isolated screens, not as systems.',
      bodyP2: 'The session covered how to structure components, states and rules so that the UI serves both the player and the team — reducing guesswork on both sides.',
      whyBelongsLabel: 'Why this belongs in my work',
      whyBelongs: 'Systems thinking is the part of my work that is hardest to show in a case study. This workshop made it concrete: how to move from decorative screens to structured, reusable UI that holds up across production, updates and team handoffs.',
      topicsLabel: 'Topics covered',
      visualsLabel: 'From the event',
      closingLabel: 'Design is also communication',
      closingHeadline: 'A strong design perspective should be useful beyond the file.',
      closingBody: 'It should help people see where friction starts, why a system matters more than a screen, and how better structure leads to better decisions, in the interface and in the work around it.',
      closingCta: 'Get in touch',
    },
    caseStatuses: {
      'public': 'Public Case Study',
      'nda-safe': 'NDA-Safe Breakdown',
      'password-protected': 'Password Protected',
      'coming-soon': 'Coming Soon',
      'legacy': 'Legacy Work',
    },
  },
  es: {
    nav: {
      status: 'Abierto a Roles',
      statusSub: 'Senior · Lead · Remoto · Internacional',
      menu: 'MENU +',
      logoLabel: 'ByAndresFe — volver al inicio',
      logoSub: 'ByAndresFe',
      work: 'Trabajo',
      about: 'Sobre mí',
      resume: 'CV',
      notes: 'Notas',
      contact: 'Contacto',
      lang: 'EN',
    },
    hero: {
      label: 'UX Lead / Diseñador Game UX/UI',
      signalActive: 'SEÑAL ACTIVA',
      focusAreasLabel: 'Áreas de enfoque actuales',
      subtitle: 'Diseñando experiencias\nque dejan\nhuella.',
      body: 'Diseño interfaces, flujos y sistemas UX para juegos, productos digitales y experiencias interactivas. Mi trabajo conecta claridad, retroalimentación, producción y toma de decisiones del jugador.',
      cta1: 'Ver trabajo seleccionado',
      cta2: 'Sobre mí',
      proof: 'Diseñador Senior Game UX/UI y UX Lead · 11+ años · Títulos VR lanzados en Meta Quest y experiencias de IP licenciado en Fortnite / UEFN — Dungeons & Dragons, Star Wars, The Walking Dead.',
      tags: ['VR UX', 'UEFN', 'Unreal', 'Roblox', 'Sistemas HUD', 'Sistemas UI', 'Claridad del jugador', 'Accesibilidad', 'Handoff de producción'],
    },
    labHero: {
      navLinks: ['Trabajo', 'Sobre mí', 'Enfoque', 'Experiencia', 'Contacto'],
      availability: 'Abierto a roles senior',
      nameplate: 'Soy Andrés Felipe Pisso',
      titleLines: ['Diseñando', 'Experiencias', 'Que Dejan Huella'],
      roles: ['Diseñador UX/UI', 'Diseñador de Juegos', 'Diseñador de Producto'],
      cta: 'Explorar mi trabajo',
      scroll: 'Scroll',
      revealHint: 'mueve el cursor para revelar',
      skills: ['Diseño UX / UI', 'Game Design', 'Producto Digital'],
      rightCopy: ['Diseño game UX', 'para títulos VR y', 'Fortnite lanzados —', 'D&D, Star Wars, TWD.'],
      basedInLabel: 'Base operativa',
      coordinates: '4.7110° N, 74.0721° W',
      systemsLabel: 'Sistemas',
      systemsStatus: 'Todo en verde',
      responseLabel: 'Respuesta',
      interfaceMode: '// Modo_interfaz',
      phaseActive: 'Activo',
      phaseScanning: 'Escaneando',
      phaseBoot: 'Inicio',
      statusLabel: 'Estado',
      online: 'Online',
      locationLabel: 'Ubicación',
      locationValue: 'Bogotá, Colombia',
      availableForWork: 'Disponible para trabajo',
    },
    trust: {
      label: 'Historial',
      stats: [
        { value: '11+', label: 'Años de experiencia' },
        { value: '70+', label: 'Proyectos interactivos' },
        { value: '8+', label: 'Casos Game UX/UI' },
        { value: '3+', label: 'Juegos lanzados' },
      ],
    },
    whatIDo: {
      label: 'Qué hago',
      sectionTitle: 'Tres dominios.\nUna restricción.',
      headline: 'Diseño en tres dominios.',
      items: [
        {
          title: 'Game UX/UI',
          body: 'HUDs, menús, onboarding, sistemas de retroalimentación, flujos de jugador, legibilidad y claridad de progresión.',
          tags: ['VR', 'UEFN', 'Unreal', 'Roblox', 'HUD', 'Onboarding', 'Fortnite'],
        },
        {
          title: 'Sistemas UX',
          body: 'Patrones de UI reutilizables, estados, componentes, reglas de interacción, documentación y handoff.',
          tags: ['Componentes', 'Design Systems', 'Handoff', 'Documentación'],
        },
        {
          title: 'Producto Digital',
          body: 'Arquitectura de información, flujos, prototipos, diseño de interfaz, usabilidad y claridad de producto.',
          tags: ['IA', 'Wireframes', 'Prototipado', 'Usabilidad'],
        },
      ],
    },
    howIWork: {
      label: 'Cómo trabajo',
      sectionTitle: 'De la duda\na la señal.',
      headline: 'De la duda a la señal.',
      body: 'Cada proyecto empieza con un loop, una brecha y una señal. El proceso es sistemático, no decorativo.',
      steps: [
        { num: '01', title: 'Entender el loop', body: 'Mapear el recorrido del jugador o usuario. Identificar dónde ocurren acciones, consecuencias y retroalimentación.' },
        { num: '02', title: 'Encontrar dónde empieza la hesitación', body: 'Localizar los puntos de fricción. ¿Qué obliga a adivinar? ¿Qué genera duda o confusión?' },
        { num: '03', title: 'Diseñar la señal', body: 'Construir la respuesta de interfaz que elimina la ambigüedad. Retroalimentación clara, mejor jerarquía, decisiones más rápidas.' },
        { num: '04', title: 'Testear la decisión', body: 'Validar el diseño contra el problema. ¿Reduce la hesitación? ¿El jugador o usuario avanza con confianza?' },
        { num: '05', title: 'Documentar el sistema', body: 'Convertir decisiones en reglas reutilizables. Componentes, estados, specs de handoff y notas de casos borde.' },
      ],
    },
    caseFiles: {
      label: 'Trabajo seleccionado',
      sectionTitle: 'DISEÑO CON CONTEXTO REAL.\nSISTEMAS, INTERFACES Y DECISIONES.',
      headline: 'Casos de estudio.',
      descriptionShort: 'Una selección de proyectos donde el diseño no ocurrió en condiciones ideales, sino dentro de objetivos, restricciones y necesidades reales de producto. Algunos casos son públicos; otros están presentados de forma NDA safe para mostrar el criterio detrás del trabajo sin comprometer información sensible.',
      description: 'Una selección de proyectos donde el diseño no ocurrió en condiciones ideales, sino dentro de objetivos, restricciones y necesidades reales de producto. Algunos casos son públicos; otros están presentados de forma NDA safe para mostrar el criterio detrás del trabajo sin comprometer información sensible.',
      viewAll: 'Ver todo el trabajo',
      openCase: 'Abrir caso',
      metaRole: 'Rol',
      metaYear: 'Año',
      metaFocus: 'Enfoque',
      project: 'proyecto',
      projects: 'proyectos',
      noProjects: 'Ningún proyecto coincide con este filtro.',
      filterLabels: { All: 'Todos', Games: 'Juegos', UEFN: 'UEFN', VR: 'VR', 'NDA-Safe': 'NDA-Safe', Legacy: 'Archivo' },
      filterNav: 'Filtrar proyectos',
      casesRegionLabel: 'Casos de estudio',
    },
    systemsLab: {
      label: 'Systems Lab',
      sectionTitle: 'Restricciones,\nno valores.',
      principlesLabel: 'Principios de diseño',
      modulesLabel: 'Módulos de trabajo activo',
      description: 'Estos no son valores aspiracionales. Son restricciones prácticas aplicadas a cada decisión de diseño. Existen porque el UX en juegos falla de maneras predecibles, y estos principios abordan los modos de falla más comunes.',
      principles: [
        { id: '01', title: 'Claridad antes que pulido', body: 'Si un jugador tiene que leer algo dos veces para entenderlo, el acabado visual no importa. La claridad va primero.' },
        { id: '02', title: 'Retroalimentación antes que suposición', body: 'El jugador siempre debe saber qué pasó, qué está pasando y qué pasará después. Si está adivinando, la interfaz ha fallado.' },
        { id: '03', title: 'Sistemas antes que pantallas aisladas', body: 'Diseñar una pantalla sin entender sus estados conectados produce interfaces que funcionan en demos y se rompen en producción.' },
        { id: '04', title: 'Útil antes que decorativo', body: 'El movimiento, el color y el detalle visual se ganan su lugar comunicando algo. La decoración que no transmite señal es ruido.' },
        { id: '05', title: 'Mejores señales, mejores decisiones', body: 'El resultado del buen UX no es una pantalla bonita. Es un jugador que tomó la decisión correcta con menos fricción que antes.' },
      ],
      modules: [
        { label: 'Revisiones de HUD', tag: 'Análisis' },
        { label: 'Sistemas UX', tag: 'Arquitectura' },
        { label: 'Componentes y estados UI', tag: 'Sistemas' },
        { label: 'Revisiones de accesibilidad', tag: 'Cumplimiento' },
        { label: 'Onboarding del jugador', tag: 'Flujos' },
        { label: 'LiveOps UX', tag: 'Producto' },
        { label: 'Workflows en Figma', tag: 'Herramientas' },
        { label: 'Workflows en UEFN', tag: 'Plataforma' },
        { label: 'Documentación', tag: 'Handoff' },
      ],
    },
    igStrip: {
      label: 'En el campo',
      viewProfile: 'Ver perfil',
      viewPost: 'Ver en Instagram',
    },
    fieldNotes: {
      label: 'Notas de campo',
      sectionTitle: 'Aplicado.\nNo teórico.',
      headline: 'Notas y marcos de trabajo.',
      description: 'Análisis, marcos de trabajo y material de referencia construido a partir de problemas reales de UX en juegos. No teoría. Probado en producción.',
      readNote: 'Leer nota',
      viewAll: 'Ver todas las notas',
    },
    about: {
      label: 'Sobre mí',
      sectionTitle: 'Diseño entre\nidea, producto y experiencia.',
      fullProfile: 'Perfil completo',
      headline: '¿Dónde se rompe la claridad?',
      bio1: 'Empecé en ingeniería de sistemas y terminé construyendo los loops de retroalimentación que los jugadores no notan cuando funcionan. Once años en juegos lanzados, experiencias UEFN en vivo, VR y producto digital.',
      bio2: 'Mi trabajo empieza con una pregunta: ¿dónde falla la claridad? En juegos, aparece como un HUD que distrae de la acción, un flujo de recompensas que genera hesitación, o un sistema de progresión que hace que los jugadores adivinen qué cambió. En producto, es navegación poco clara, retroalimentación débil, o pantallas que parecen limpias pero no ayudan a decidir.',
      bio3: 'Me importan las interfaces que reducen la duda. Señales claras. Retroalimentación útil. Sistemas que ayudan a los equipos a moverse más rápido sin perder consistencia.',
      coreQuestion: '"¿Dónde está adivinando el jugador?"',
      coreQuestionLabel: 'Pregunta central',
      philosophy: 'El buen UX para juegos no es invisible. Es suficientemente presente y claro para que el jugador nunca tenga que pensar en la interfaz.',
      philosophyLabel: 'Filosofía de diseño',
      availabilityLabel: 'Disponibilidad',
      availabilityStatus: 'Abierto a roles Senior y Lead en Game UX/UI y UX/UI Lead',
      availabilityContext: 'Remoto · Híbrido · Estudios internacionales — posiciones Senior y Lead',
      availabilityCta: 'Escribir',
      expertiseLabel: 'Áreas de expertise',
      timelineLabel: 'Trayectoria',
      languagesLabel: 'Idiomas',
      languages: ['Español — Nativo', 'Inglés — Competencia profesional avanzada'],
      educationLabel: 'Formación',
      education: [
        { year: '2023', degree: 'Maestría en Diseño Gráfico Digital', institution: 'UNIR — Universidad Internacional de La Rioja' },
        { year: '2019', degree: 'Especialista en Auditoría de Sistemas de Información', institution: 'Universidad Católica de Colombia' },
        { year: '2016', degree: 'Especialista en Diseño y Desarrollo de Videojuegos', institution: 'Michigan State University' },
        { year: '2015', degree: 'Ingeniero de Sistemas', institution: 'Universidad Cooperativa de Colombia' },
      ],
      certificationsLabel: 'Certificaciones',
      certifications: [
        { year: '2024', label: 'Epic Games Game Design Professional Certificate', note: 'En curso' },
        { year: '2015', label: 'Gamification', note: 'University of Pennsylvania' },
      ],
      timeline: [
        { period: '2025 – Hoy', role: 'Lead UX/UI Designer', context: 'Teravision Games · Orcs Must Die, UEFN, VR, D&D' },
        { period: '2023 – 2025', role: 'Lead Game Designer', context: 'PixieMeta · Juegos móviles, sistemas UX' },
        { period: '2022 – 2023', role: 'Líder de Uso y Adopción TI', context: 'Ministerio TIC Colombia · Transformación digital, GAMETIC' },
        { period: '2016 – 2022', role: 'Game Designer / Ingeniero de Sistemas', context: 'Ministerio TIC Colombia · 70+ apps, 20 juegos, GAMETIC' },
        { period: '2015 – 2016', role: 'Game Designer / Director de Proyecto', context: 'U. Cooperativa · Kodety — ganador Colombia Crea Digital' },
      ],
      hiringSnapshot: 'Diseñador Senior Game UX/UI y UX Lead con 11+ años en juegos, productos digitales y experiencias interactivas. Me especializo en sistemas UI, claridad de HUD, VR UX, experiencias UEFN, onboarding, flujos de progresión, retroalimentación para el jugador, accesibilidad y documentación lista para producción. Mi trabajo conecta el entendimiento del jugador con la ejecución del equipo a través de flujos claros, componentes reutilizables, interfaces legibles y handoff listo para implementación.',
      hiringSnapshotLabel: 'Perfil para Reclutadores',
      hiringSnapshotRoles: 'Abierto a roles de Senior Game UX/UI Designer, UX/UI Lead, Game UI Systems Designer y UX Lead en equipos remotos, híbridos e internacionales.',
      recruiterSummaryLabel: 'Resumen para Reclutadores',
      recruiterSummaryTargetLabel: 'Roles objetivo',
      recruiterSummaryTarget: 'Senior Game UX/UI Designer · UX/UI Lead · Game UI Systems Designer · UX Lead',
      recruiterSummaryStrengthsLabel: 'Fortalezas clave',
      recruiterSummaryStrengths: [
        'Estrategia Game UX/UI y diseño de sistemas',
        'Sistemas UI, lógica de componentes y librerías de patrones reutilizables',
        'Claridad de HUD, retroalimentación del jugador y legibilidad',
        'VR UX y consideraciones de interfaz espacial',
        'Diseño y handoff con consciencia de UEFN y Unreal',
        'Onboarding, FTUX y flujos de progresión',
        'Accesibilidad y legibilidad de interfaces',
        'Documentación lista para producción para diseño, arte, ingeniería, QA y producción',
        'Colaboración cross-funcional entre disciplinas',
      ],
      recruiterSummaryToolsLabel: 'Herramientas',
      recruiterSummaryTools: 'Figma · Unreal Engine · contexto UEFN · Roblox · Jira · Confluence · Adobe Creative Suite · herramientas de prototipado · sistemas de documentación',
      recruiterSummaryTeamsLabel: 'Equipos ideales',
      recruiterSummaryTeams: 'Estudios de juegos · equipos UEFN · proyectos VR · juegos live · experiencias con IP licenciadas · equipos de sistemas UI · equipos UX trabajando cerca de implementación',
      seniorValueLabel: 'Por qué esto importa para roles senior',
      seniorValue: 'El trabajo Senior en Game UX/UI no se trata solo de hacer que las interfaces se vean pulidas. Se trata de ayudar a los jugadores a entender lo que importa, ayudar a los equipos a reutilizar decisiones, reducir la ambigüedad en producción y diseñar sistemas que sobrevivan la iteración. Mi trabajo más fuerte está en esa intersección: claridad del jugador, sistemas UI, documentación, handoff de implementación y colaboración cross-funcional.',
      aboutCtaHeadline: 'Si tu equipo está construyendo algo que los jugadores deben entender,',
      aboutCtaAccent: 'puedo ayudar.',
      aboutCtaEmail: 'Enviar señal',
      aboutCtaLinkedIn: 'LinkedIn',
      resumeBtn: 'Descargar CV — Senior Game UX/UI / UX Lead',
      expertise: [
        'Game UX/UI', 'Liderazgo UX', 'Sistemas UI', 'Product Thinking',
        'Game Design', 'Documentación', 'Accesibilidad', 'UEFN / Unreal',
        'Colaboración cross-funcional', 'Player Onboarding', 'HUD Design', 'LiveOps UX', 'VR UX',
      ],
      skillGroups: [
        { title: 'Game UX/UI', items: ['HUD', 'Menús', 'Onboarding', 'Progresión', 'Flujos de recompensa', 'Retroalimentación', 'Legibilidad', 'Player loops', 'VR UX', 'UEFN UX'] },
        { title: 'Sistemas UX', items: ['Design systems', 'Componentes', 'Estados', 'Patrones', 'Documentación', 'Handoff', 'Soporte QA', 'Revisiones de accesibilidad'] },
        { title: 'Producto UX/UI', items: ['Arquitectura de información', 'Flujos', 'Wireframes', 'Prototipos', 'Usabilidad', 'Diseño de interfaz', 'Alineación de stakeholders'] },
        { title: 'Herramientas', items: ['Figma', 'FigJam', 'UEFN', 'Unreal', 'Roblox', 'Claude', 'Jira', 'Confluence', 'Adobe tools', 'Herramientas de prototipado'] },
      ],
    },
    contact: {
      label: 'Contacto / Señal',
      channelsLabel: 'Canales de contacto',
      linkedinCta: 'Agendar llamada en LinkedIn',
      contactMe: 'Contáctame →',
      headline: 'Estoy abierto a roles de Senior Game UX/UI, UX Lead, UX/UI Lead y Game UI Systems Designer, en equipos remotos, híbridos o internacionales.',
      ctaLine1: 'Construyamos',
      ctaStroke: 'experiencias',
      ctaLine3: 'más claras.',
      cta: 'Enviar señal',
      email: 'hi@byandresfe.com',
      linkedin: 'linkedin.com/in/byandresfe',
      instagram: '@byandresfe',
      x: '@byandresfe',
      location: 'Colombia — remoto e internacional',
      formLabels: {
        name: 'Nombre',
        email: 'Email',
        company: 'Empresa o estudio',
        type: 'Tipo de oportunidad',
        message: 'Mensaje',
        send: 'Enviar mensaje',
        sending: 'Enviando...',
        success: 'Mensaje recibido. Te respondo en los próximos días.',
      },
      opportunityTypes: ['Rol en estudio', 'Rol en producto', 'Proyecto freelance', 'Consultoría', 'Charla o taller', 'Otro'],
    },
    footer: {
      tagline: 'UX/UI para juegos y producto digital enfocado en claridad, retroalimentación y mejores decisiones.',
      links: ['Trabajo', 'Sobre mí', 'CV', 'Notas', 'Contacto'],
      copy: '© 2026 Andrés Felipe Pisso',
      handle: '@byandresfe',
      navWork: 'Trabajo',
      navConnect: 'Conectar',
      resume: 'CV',
    },
    resume: {
      label: 'CV',
      headline: 'Andrés Felipe Pisso',
      subheadline: 'UX Lead · Diseñador Game UX/UI',
      download: 'Descargar PDF',
      sections: {
        summary: 'Resumen',
        experience: 'Experiencia seleccionada',
        projects: 'Proyectos seleccionados',
        skills: 'Habilidades',
        tools: 'Herramientas',
        education: 'Educación',
        languages: 'Idiomas',
        contact: 'Contacto',
      },
      summary: '11+ años diseñando sistemas UX/UI para juegos, productos digitales y experiencias interactivas. Enfocado en claridad, retroalimentación, toma de decisiones del jugador e interfaces listas para producción. Experiencia en VR, UEFN, mobile y producto digital.',
      experience: [
        {
          period: '2025 – Hoy',
          role: 'Lead UX/UI Designer',
          company: 'Teravision Games',
          description: 'UX Lead en proyectos de juego publicados, experiencias live en Fortnite / UEFN y producciones VR. Responsable de estrategia UX, diseño de sistemas UI, documentación de diseño y colaboración cross-disciplina.',
        },
        {
          period: '2023 – 2025',
          role: 'Lead Game Designer',
          company: 'PixieMeta',
          description: 'Definí y mantuve la visión creativa de juegos móviles, alineando sistemas de gameplay, flujos de usuario y decisiones UI/UX con las necesidades del público y los objetivos de negocio.',
        },
        {
          period: '2016 – 2023',
          role: 'Ingeniero de Sistemas / Game Designer / Diseñador UX',
          company: 'Diversas organizaciones',
          description: 'Diseño de juegos, diseño de interacción, UI/UX y producto digital en iniciativas de tecnología gubernamental, plataformas educativas y experiencias web interactivas.',
        },
      ],
      projects: [
        { title: 'Star Wars: Roguelike One', type: 'UEFN / Game UX/UI', year: '2026' },
        { title: 'Orcs Must Die: By the Blade', type: 'VR Game UX/UI', year: '2025–2026' },
        { title: 'D&D: Zombie Dragon Adventure', type: 'UEFN / Game UX/UI', year: '2025' },
        { title: 'The Walking Dead: Courtyard King', type: 'UEFN / Game UX/UI', year: '2025' },
        { title: 'Raptor Heist', type: 'UEFN / Game UX/UI', year: '2025' },
        { title: 'Havoc Hotel 3', type: 'UEFN / UX Systems', year: '2025' },
      ],
      languageList: ['Español — Nativo', 'Inglés — Profesional'],
      locationRemote: 'Colombia — Remoto',
    },
    casePage: {
      notFound: 'Caso no encontrado.',
      backToWork: '← Volver al trabajo',
      metaRole: 'Rol',
      metaPlatform: 'Plataforma',
      metaYear: 'Año',
      quickFacts: 'Datos rápidos',
      prev: '← Anterior',
      next: 'Siguiente →',
      sections: {
        executiveSummary: 'Resumen ejecutivo',
        context: 'Contexto',
        challenge: 'El desafío',
        myRole: 'Mi rol',
        constraints: 'Restricciones',
        uxApproach: 'Enfoque UX',
        keyDecisions: 'Decisiones clave',
        keyDecisionsIntro: 'Estas son las decisiones de diseño que definieron los resultados UX más importantes del proyecto.',
        problem: 'Problema',
        decision: 'Decisión',
        whyItMattered: 'Por qué importó',
        deliverables: 'Entregables',
        outcome: 'Resultado',
        projectSnapshot: 'Snapshot del proyecto',
        myOwnership: 'Mi responsabilidad',
        impact: 'Impacto / Evidencia',
        implementationHandoff: 'Implementación y entrega',
        researchValidation: 'Investigación y validación',
        nextSteps: 'Lo que revisaría después',
        whatThisShows: 'Lo que este proyecto muestra',
        featuredSystems: 'Sistemas destacados',
        beforeAfter: 'Antes y después',
        whatILearned: 'Lo que aprendí',
        playerExperienceLoop: 'Loop de experiencia del jugador',
      },
      fieldLabels: {
        role: 'Rol',
        studio: 'Estudio',
        client: 'Cliente',
        IP: 'IP',
        platform: 'Plataforma',
        type: 'Tipo',
        duration: 'Duración',
        team: 'Equipo',
        tools: 'Herramientas',
        status: 'Estado',
        engine: 'Motor',
        context: 'Contexto',
        mainChallenge: 'Desafío principal',
        keyDeliverables: 'Entregables clave',
        constraints: 'Restricciones',
      },
    },
    notFound: {
      tag: 'Error 404',
      subtitle: 'Página desconectada.',
      bodyPrefix: 'La página',
      bodySuffix: 'está offline. Encontramos el problema — un pequeño sospechoso marrón escapó con el cable antes de que esta página pudiera cargar.',
      logs: [
        'ESTADO_PÁGINA: OFFLINE',
        'ESTADO_CABLE: EN BOCA DEL PERRO',
        'ESTADO_OPERADOR: EN PÁNICO',
        'DESCRIPCIÓN_SOSPECHOSO: MARRÓN, RÁPIDO, CON HOODIE',
        'PLAN_RECUPERACIÓN: CORRER MÁS RÁPIDO',
      ],
      cta: 'Restaurar Conexión',
      pageTitle: 'Página No Encontrada — AFPISSO',
      pageDesc: 'La página que buscabas ha desaparecido. Puede que un perro esté involucrado.',
    },
    aboutPage: {
      subheadline: 'UX Lead · Diseñador Game UX/UI',
    },
    contactOverlay: {
      signalContact: 'Señal de Contacto',
      directChannel: 'CANAL DIRECTO',
      primaryChannel: 'Canal principal',
      writeCta: 'ESCRIBIR →',
      tagProfessional: 'Profesional',
      tagCreative: 'Creativo',
      tagSignal: 'Señal',
    },
    notePage: {
      comingSoon: 'Esta nota estará disponible pronto.',
      notFound: 'Nota no encontrada.',
      backToNotes: 'Volver a notas de campo',
      aboutNote: 'Sobre esta nota',
      metaId: 'ID',
      metaType: 'Tipo',
      metaReadTime: 'Lectura',
      metaCategory: 'Categoría',
      metaPublished: 'Publicado',
      nextNote: 'Siguiente nota',
      fieldNotesLabel: 'Notas de campo',
      subscribeHeadline: 'Recibe las próximas notas',
      subscribeBody: 'Game UX, sistemas de UI, accesibilidad y decisiones de diseño. Sin spam.',
      subscribePlaceholder: 'tu@email.com',
      subscribeCta: 'Suscribirse',
      subscribeSuccess: 'Te responderé pronto.',
      relatedCaseStudies: 'Casos relacionados',
      openCase: 'Abrir caso',
      allNotes: 'Todas las notas',
      nextNoteCta: 'Siguiente',
    },
    casePage_cta: {
      body: 'Si mi trabajo encaja con tu equipo o proyecto, contactarme debería tomar menos de un minuto.',
    },
    speaking: {
      sectionLabel: 'Speaking & Workshops',
      heroSubtitle: 'Game UI Systems: de pantallas bonitas a interfaces que funcionan.',
      contextLabel: 'El taller',
      bodyP1: 'En Colombia 5.0 impartí un taller sobre Game UI Systems: específicamente sobre cómo construir un sistema de UI reutilizable y funcional para videojuegos usando Figma. La premisa: la mayoría de interfaces de juegos se ven pulidas pero se rompen en condiciones reales de producción porque fueron diseñadas como pantallas aisladas, no como sistemas.',
      bodyP2: 'La sesión cubrió cómo estructurar componentes, estados y reglas para que la UI le sirva tanto al jugador como al equipo — reduciendo la ambigüedad en ambos lados.',
      whyBelongsLabel: 'Por qué esto es parte de mi trabajo',
      whyBelongs: 'El pensamiento sistémico es la parte de mi trabajo más difícil de mostrar en un caso de estudio. Este taller lo hizo concreto: cómo pasar de pantallas decorativas a UI estructurada y reutilizable que aguanta producción, actualizaciones y handoffs de equipo.',
      topicsLabel: 'Temas tratados',
      visualsLabel: 'Del evento',
      closingLabel: 'El diseño también es comunicación',
      closingHeadline: 'Una perspectiva de diseño sólida debe ser útil más allá del archivo.',
      closingBody: 'Debe ayudar a equipos, estudiantes y profesionales a ver dónde empieza la fricción, por qué un sistema importa más que una pantalla, y cómo mejor estructura lleva a mejores decisiones, tanto en la interfaz como en producción.',
      closingCta: 'Escribir',
    },
    caseStatuses: {
      'public': 'Caso de estudio público',
      'nda-safe': 'Análisis NDA-Safe',
      'password-protected': 'Protegido con contraseña',
      'coming-soon': 'Próximamente',
      'legacy': 'Trabajo pasado',
    },
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    let stored = null;
    try { stored = localStorage.getItem('lang'); } catch (_) { /* storage unavailable */ }
    if (stored === 'en' || stored === 'es') return stored;
    // Auto-detect from browser and persist immediately so every subsequent
    // page load (refresh, new tab, direct URL) uses the same language.
    const browser = navigator.language.slice(0, 2).toLowerCase();
    const detected = browser === 'es' ? 'es' : 'en';
    try { localStorage.setItem('lang', detected); } catch (_) { /* storage unavailable */ }
    return detected;
  });

  // Keep <html lang="…"> in sync with the active language
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  function toggleLang() {
    const next = lang === 'en' ? 'es' : 'en';
    setLang(next);
    try { localStorage.setItem('lang', next); } catch (_) { /* storage unavailable */ }
  }

  function changeLang(l) {
    if (l !== 'en' && l !== 'es') return;
    setLang(l);
    try { localStorage.setItem('lang', l); } catch (_) { /* storage unavailable */ }
  }

  const value = useMemo(
    () => ({ lang, toggleLang, setLang: changeLang, t: translations[lang] }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [lang]
  );

  return (
    <LangContext.Provider value={value}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used inside LangProvider');
  return ctx;
}
